# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


articles = Article.create([{title: 'Lorem Ispum', thumbnail: "http://www.foreverfitness24.com/wp-content/uploads/2014/08/gym.jpg", content: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce et libero a turpis sagittis maximus. Nam mattis risus in arcu aliquet ultricies et quis mi. Sed maximus eget dui a cursus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis sit amet sapien eleifend, placerat tellus vel, porta risus. Curabitur consequat imperdiet nunc ac fringilla. Vestibulum sagittis sodales nisl, non iaculis magna lacinia et. Duis consectetur enim nec aliquam porttitor. Etiam sed auctor ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed lectus neque, iaculis rhoncus viverra sed, accumsan ut orci. Integer placerat id massa vel interdum. Mauris dignissim turpis erat, nec molestie felis bibendum ac. Mauris nibh ex, molestie ac semper id, facilisis ac felis. Maecenas dictum interdum nulla, et consectetur erat consectetur eu. Donec ut leo eget velit elementum molestie ac vel augue.

Donec laoreet, justo id tincidunt congue, felis libero rutrum enim, eu efficitur risus neque at tellus. Phasellus molestie magna magna, id pellentesque velit molestie eget. Fusce lobortis urna placerat nibh volutpat molestie. Etiam non varius ligula. Aliquam quis nulla pharetra, ultrices nisi vitae, dictum ante. Pellentesque posuere eu diam in finibus. In feugiat enim a dictum pretium. Aliquam turpis ante, condimentum porttitor lacus ut, ultrices facilisis mi. Phasellus eleifend ipsum vitae cursus tincidunt. Nunc hendrerit odio vulputate condimentum interdum. Vestibulum id sagittis nulla, sit amet molestie lorem. Ut mollis nibh massa, at consequat risus maximus ac.

Duis malesuada tellus eget mauris tincidunt ultricies. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum semper, purus vel mollis convallis, ligula nibh auctor est, sed luctus massa justo at orci. Praesent vitae ante nec nulla lacinia rhoncus varius et sapien. Donec dictum eleifend quam faucibus pharetra. Nulla facilisi. Integer at elit quis neque efficitur aliquet. Maecenas sem mi, placerat vel metus vel, egestas gravida nisi. Morbi vestibulum pulvinar neque, eget commodo ipsum hendrerit eu. Nulla consectetur sed libero vel tincidunt. Aenean dictum posuere felis tempor convallis. Quisque non tempus metus. Suspendisse congue interdum urna, eget maximus dolor congue sollicitudin. "}])